likelion10th/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    #로그아웃 기능인데 혹시 필요할지도 몰라 만들어 보았습니다.
    path('logout/', views.Logout, name='logout'),
    #탈퇴 기능인데 혹시 필요할지도 몰라 만들어 보았습니다.
    path('secession/',views.secession, name='secession'),

    path('login/kakao/', views.kakao_login, name="kakao-login"),
    path('login/kakao/callback/', views.kakao_callback, name='kakao-callback'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy')
]

likelion10th/apply/urls.py
from unicodedata import name
from django.urls import path
from . import views #현재 폴더에 있는 views에 접근하기 때문

app_name = 'apply' # app_name에는 앱 이름을 넣어줍니다.

urlpatterns = [
    path('create/', views.create, name='create'),
    path('update/', views.update, name='update'),
    path('mypage/', views.mydetail, name='mydetail'),
    path('submit/', views.submit, name='submit')
]

likelion10th/likelion10th/urls.py
from django.contrib import admin
from django.urls import path, include
from apply import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('apply/', include('apply.urls')),
    path('account/', include('account.urls')),

    path('results/', include('pass_or_fail.urls')),
    
]

likelion10th/pass_or_fail/urls.py
from django.urls import path
from . import views #현재 폴더에 있는 views에 접근하기 때문

app_name = 'pass_or_fail' # app_name에는 앱 이름을 넣어줍니다.

urlpatterns = [
    
     path('', views.pass_or_fail, name='pass_or_fail'),
    
]

likelion10th/likelion10th/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- SEO Meta Tags -->
    <meta name="description" content="Tivo is a HTML landing page template built with Bootstrap to help you crate engaging presentations for SaaS apps and convert visitors into users.">
    <meta name="author" content="Inovatik">

    <!-- OG Meta Tags to improve the way the post looks when you share the page on LinkedIn, Facebook, Google+ -->
	<meta property="og:site_name" content="" /> <!-- website name -->
	<meta property="og:site" content="" /> <!-- website link -->
	<meta property="og:title" content=""/> <!-- title shown in the actual shared post -->
	<meta property="og:description" content="" /> <!-- description shown in the actual shared post -->
	<meta property="og:image" content="" /> <!-- image link, make sure it's jpg -->
	<meta property="og:url" content="" /> <!-- where do you want your post to link to -->
	<meta property="og:type" content="article" />

    <!-- Website Title -->
    <title>{%block title %}멋쟁이사자처럼 한국외대(서울){% endblock %}</title>
    
    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap&subset=latin-ext" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet">
    <link href="{% static 'css/swiper.css' %}" rel="stylesheet">
	<link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
	{% block style %}
    {% endblock %}
	<!-- Favicon  -->
    <link rel="icon" href="{% static 'images/ll_favicon.png'%}">
</head>
<body data-spy="scroll" data-target=".fixed-top">
    
    <!-- Preloader -->
	<div class="spinner-wrapper">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->
    

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container">

            <!-- Text Logo - Use this if you don't have a graphic logo -->
            <!-- <a class="navbar-brand logo-text page-scroll" href="index.html">Tivo</a> -->

            <!-- Image Logo -->
            <a class="navbar-brand logo-image" href="{% url 'home' %}"><img src="{% static 'images/ll_logo.png' %}" alt="alternative" style="width: 80%;"></a> 
            
            <!-- Mobile Menu Toggle Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-awesome fas fa-bars"></span>
                <span class="navbar-toggler-awesome fas fa-times"></span>
            </button>
            <!-- end of mobile menu toggle button -->

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'home' %}">HOME <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="https://emerald-gouda-9bd.notion.site/24add311de0d4201af92f68cf5d16587">멋사 소개</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'apply:mydetail' %}">지원서 작성하기</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="{% url 'pass_or_fail:pass_or_fail' %}" >합격 조회</a>
                    </li>
                </ul>
                <span class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="btn-outline-sm" href="{% url 'account:logout' %}">로그아웃</a>
                    {% else %}
                        <a class="btn-outline-sm" href="{% url 'account:login' %}">로그인</a>
                    {% endif %}
                </span>
            </div>
        </div> <!-- end of container -->
    </nav> <!-- end of navbar -->
    <!-- end of navigation -->

    {% block content %}

    {%endblock%}
    
    <!-- Copyright -->
    <div class="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="p-small">멋쟁이사자처럼 한국외대(서울)<br>
                        이메일 <a href="mailto:hufs_seoul@likelion.org" target="_blank">hufs_seoul@likelion.org</a>
                    </p>
                </div> <!-- end of col -->
            </div> <!-- enf of row -->
        </div> <!-- end of container -->
    </div> <!-- end of copyright --> 
    <!-- end of copyright -->
    
    	
    <!-- Scripts -->
    <script src="{% static 'js/jquery.min.js'%}"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
    <script src="{% static 'js/popper.min.js'%}"></script> <!-- Popper tooltip library for Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js'%}"></script> <!-- Bootstrap framework -->
    <script src="{% static 'js/jquery.easing.min.js'%}"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src="{% static 'js/swiper.min.js'%}"></script> <!-- Swiper for image and text sliders -->
    <script src="{% static 'js/jquery.magnific-popup.js'%}"></script> <!-- Magnific Popup for lightboxes -->
    <script src="{% static 'js/scripts.js'%}"></script> <!-- Custom scripts -->
</body>
</html>