likelion10th/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    #로그아웃 기능인데 혹시 필요할지도 몰라 만들어 보았습니다.
    path('logout/', views.Logout, name='logout'),
    #탈퇴 기능인데 혹시 필요할지도 몰라 만들어 보았습니다.
    path('secession/',views.secession, name='secession'),

    path('login/kakao/', views.kakao_login, name="kakao-login"),
    path('login/kakao/callback/', views.kakao_callback, name='kakao-callback'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy')
]

likelion10th/apply/urls.py
from unicodedata import name
from django.urls import path
from . import views #현재 폴더에 있는 views에 접근하기 때문

app_name = 'apply' # app_name에는 앱 이름을 넣어줍니다.

urlpatterns = [
    path('create/', views.create, name='create'),
    path('update/', views.update, name='update'),
    path('mypage/', views.mydetail, name='mydetail'),
    path('submit/', views.submit, name='submit')
]

likelion10th/likelion10th/urls.py
from django.contrib import admin
from django.urls import path, include
from apply import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('apply/', include('apply.urls')),
    path('account/', include('account.urls')),

    path('results/', include('pass_or_fail.urls')),
    
]

likelion10th/apply/models.py
from django.db import models
from account.models import User


#이는 아래 category 필드에서 사용되는 초이스 입니다. 우리가 흔히 웹사이트에서 무언가를 선택할 때 사용되는 select 안에 들어간다고 생각하시면 됩니다.
CATEGORY_CHOICES = (
    ("P/D","기획/디자인"),
    ("FE","프론트엔드"),
    ("BE","벡엔드")
)

#공통적으로 등장하는 verbose_name 은 db에서 보다 간편하게 필드가 무엇을 의미하는지 알 수 있도록 해주는 역할이라고 생각하시면 될 것 같습니다.
class Apply(models.Model):
    """"Model definition for Apply"""
    
    user = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        #related_name은 유저 모델에서 apply라는 모델이 어떻게 표시될지(?) 어떤 이름으로 나타날지 설정해줍니다.\
        related_name="apply",
        verbose_name="지원자",
        null=False,
    )
    category = models.CharField(
        max_length=10,
        choices = CATEGORY_CHOICES,
        null=False,
        #choice의 기본값을 설정해줍니다.
        default="P/D",
    )
    study_url = models.CharField(
        max_length=2100,
        null=True,
        verbose_name="깃헙/블로그 링크",
    )
    first_q = models.TextField(
        null=False,
        verbose_name="질문 1",
    )
    second_q = models.TextField(
        null=False,
        verbose_name="질문 2",
    )
    third_q = models.TextField(
        null=False,
        verbose_name="질문 3",
    )
    fourth_q = models.TextField(
        null=False,
        verbose_name="질문 4"
    )
    is_submitted= models.BooleanField(
        null=False,
        default=False,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )
    class Meta:
        managed = False
        db_table = 'apply'

likelion10th/apply/views.py
from django.shortcuts import render, redirect
from .models import Apply
from django.contrib.auth.decorators import login_required


# Create your views here.
def home(request):
    return render(request, 'home.html')

@login_required(login_url='/account/login/')
def create(request):
    if Apply.objects.filter(user=request.user).exists():
        return redirect('apply:mydetail')  # 작성한 폼이 존재할 경우, detail or update 페이지로 넘어갑니다.
    if request.method == 'POST':   # 지원폼 작성 후 저장
        new_application = Apply()
        new_application.user = request.user   # user name
        new_application.category = request.POST['category']   # category
        new_application.study_url = request.POST['study_url']   # 깃헙 / 블로그 주소
        new_application.first_q = request.POST['q1']   # 질문 1
        new_application.second_q = request.POST['q2']   # 질문 2
        new_application.third_q = request.POST['q3']   # 질문 3
        new_application.fourth_q = request.POST['q4']   # 질문 4
        new_application.save()
        return redirect('apply:mydetail')
    return render(request, 'create.html')   # 로그인이 되어 있고 작성한 폼이 존재하지 않는 경우, create 페이지로 넘어갑니다.


def update(request):
    try:
        application = Apply.objects.get(user=request.user)
        if request.method == 'POST' and application.is_submitted == False:
            application.category = request.POST['category']   # category
            application.study_url = request.POST['study_url']   # 깃헙 / 블로그 주소
            application.first_q = request.POST['q1']   # 질문 1
            application.second_q = request.POST['q2']   # 질문 2
            application.third_q = request.POST['q3']   # 질문 3
            application.fourth_q = request.POST['q4']   # 질문 4
            application.save()
            return redirect('apply:mydetail')   # detail 페이지로 수정해야 함
        return render(request, 'update.html', {'apply': application})
    except Apply.DoesNotExist:
        return redirect('apply:create')

@login_required(login_url='/account/login/')
def mydetail(request):
    try: 
        apply = Apply.objects.get(user = request.user)
        return render(request, 'mydetail.html', {'apply':apply})
    except Apply.DoesNotExist:
        return redirect('apply:create')

@login_required(login_url='/account/login/')
def submit(request):
    application = Apply.objects.get(user = request.user)
    application.is_submitted = True
    application.save()
    return redirect('home')

likelion10th/apply/templates/create.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    
    <!-- Preloader -->
	<div class="spinner-wrapper">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->

    <!-- Header -->
    <header id="header" class="ex-2-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>지원서 작성</h1>
                    <p>문항을 읽고 지원서를 작성해주세요</p> 
                    <!-- apply Form -->
                    <div class="form-container" style="max-width: 80rem;">
                        <form action="{% url 'apply:create' %}" method="post">
                            {%csrf_token%}
                            <br>
                            <div class="form-group">
                                1. 다양한 IT동아리 중에서 멋쟁이사자처럼 대학 10기를 선택하고 지원하시게 된 이유를 작성해주세요. (500자 이내)
                                <textarea name="q1" class="form-control-input" rows="10"></textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <div class="form-group">
                                2-1. 멋쟁이사자처럼 대학 10기부터 기초 개발 스터디는 동일하게 진행되지만 이후에 기획/디자인 파트와 개발 파트 중 선택하여 진행하게 됩니다.<br>어느 파트에 지원하시나요?
                                <select style="width:180px;" name="category" class="form-control-select" id="spassword">
                                    <option value="P/D">기획/디자인</option>
                                    <option value="FE">프론트엔드</option>
                                    <option value="BE">백엔드</option>
                                </select>
                            </div>
                            <br>
                            <div class="form-group">
                                2-2. 위의 파트를 선택한 이유와 관련 경험을 해본 적이 있는지, 그리고 이 파트를 통해 어떠한 성장을 희망하는지 작성해주세요. (500자 이내)
                                <textarea name="q2" class="form-control-input" rows="10"></textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <div class="form-group">
                                3. 멋쟁이사자처럼 대학은 협업과 팀워크를 중요한 가치로 생각하는 공동체입니다. 지원자 본인이 협업과 팀워크를 진행해보았던 경험과, 그 경험을<br>멋쟁이 사자처럼 대학에서 어떻게 적용시킬 수 있을지 작성해주세요. (500자 이내)
                                <textarea name="q3" class="form-control-input" rows="10"></textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <div class="form-group">
                                4. 멋쟁이사자처럼 대학은 최소 주 2회 모임 & 10시간 이상의 시간 투자를 권장합니다. 활동 기간 동안 얼마나 열정적으로, 매주 얼만큼의 시간을 할애하실 수 있는지 작성해주세요. (500자 이내)
                                <textarea name="q4" class="form-control-input" rows="10"></textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <div class="form-group">
                                5. 깃허브 주소 혹은 기술 블로그 링크 (선택 사항)
                                <input type="text" name="study_url" class="form-control-select" >
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <br>
                            <button type="submit" name="draft" class="form-control-submit-button">임시저장</button>
                        </form>
                    </div> <!-- end of form container -->
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header> <!-- end of ex-header -->
    <!-- end of header -->
{% endblock %}

likelion10th/apply/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Header -->
<header id="header" class="header">
    <div class="header-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-xl-5">
                    <div class="text-container">
                        <h1>멋쟁이사자처럼</br> 10th</h1>
                        <p class="p-large">멋쟁이사자처럼 한국외대(서울)에서</br> 나만의 IT 서비스를 꿈꾸는 인재들을 모집합니다. </p>
                        {% if not user.is_authenticated %}
                            <a class="btn-solid-lg page-scroll" href="{% url 'account:signup' %}">회원가입</a>
                        {% endif %}
                    </div> <!-- end of text-container -->
                </div> <!-- end of col -->
                <div class="col-lg-6 col-xl-7">
                    <div class="image-container">
                        <div class="img-wrapper">
                            <img class="img-fluid" src="{% static 'images/hack_your_life.png' %}" alt="alternative">
                        </div> <!-- end of img-wrapper -->
                    </div> <!-- end of image-container -->
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of header-content -->

</header> <!-- end of header -->
<svg class="header-frame" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" viewBox="0 0 1920 310"><defs><style>.cls-1{fill:#111111;}</style></defs><title>header-frame</title><path class="cls-1" d="M0,283.054c22.75,12.98,53.1,15.2,70.635,14.808,92.115-2.077,238.3-79.9,354.895-79.938,59.97-.019,106.17,18.059,141.58,34,47.778,21.511,47.778,21.511,90,38.938,28.418,11.731,85.344,26.169,152.992,17.971,68.127-8.255,115.933-34.963,166.492-67.393,37.467-24.032,148.6-112.008,171.753-127.963,27.951-19.26,87.771-81.155,180.71-89.341,72.016-6.343,105.479,12.388,157.434,35.467,69.73,30.976,168.93,92.28,256.514,89.405,100.992-3.315,140.276-41.7,177-64.9V0.24H0V283.054Z"/></svg>
<!-- end of header -->

<!-- Footer -->
<svg class="footer-frame" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" viewBox="0 0 1920 79"><defs><style>.cls-2{fill:#fff;}</style></defs><title>footer-frame</title><path class="cls-2" d="M0,72.427C143,12.138,255.5,4.577,328.644,7.943c147.721,6.8,183.881,60.242,320.83,53.737,143-6.793,167.826-68.128,293-60.9,109.095,6.3,115.68,54.364,225.251,57.319,113.58,3.064,138.8-47.711,251.189-41.8,104.012,5.474,109.713,50.4,197.369,46.572,89.549-3.91,124.375-52.563,227.622-50.155A338.646,338.646,0,0,1,1920,23.467V79.75H0V72.427Z" transform="translate(0 -0.188)"/></svg>
{% endblock %}

likelion10th/apply/templates/mydetail.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

    <!-- Header -->
    <header id="header" class="ex-header">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>지원서 작성</h1>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header> <!-- end of ex-header -->
    <!-- end of header -->
        <!-- Privacy Content -->
        <div class="ex-basic-2">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-container">
                            <h4>1. 다양한 IT동아리 중에서 멋쟁이사자처럼 대학 10기를 선택하고 지원하시게 된 이유를 작성해주세요. (500자 이내)</h4>
                            <div class="text-container dark">
                                <p class="testimonial-text">{{apply.first_q}}</p>
                            </div> <!-- end of text container -->

                            <h4>2-1.  멋쟁이사자처럼 대학 10기부터 기초 개발 스터디는 동일하게 진행되지만 이후에 기획/디자인 파트와 개발 파트 중 선택하여 진행하게 됩니다.
어느 파트에 지원하시나요?</h4>
                            <div class="text-container dark">
                                {% if apply.category == 'P/D' %}<p class="testimonial-text">기획 / 디자인</p>
                                {% elif apply.category == 'FE' %}<p class="testimonial-text">프론트엔드</p>
                                {% else %}<p class="testimonial-text">백엔드</p>
                                {% endif %}
                            </div> <!-- end of text container -->
                            
                            <h4>2-2. 지원하신 파트를 선택한 이유와 관련 경험을 해본 적이 있는지, 그리고 이 파트를 통해 어떠한 성장을 희망하시는지 작성해주세요. (500자 이내)</h4>
                            <div class="text-container dark">
                                <p class="testimonial-text">{{apply.second_q}}</p>
                            </div> <!-- end of text container -->
    
                            <h4>3. 멋쟁이사자처럼 대학은 협업과 팀워크를 중요한 가치로 생각하는 공동체입니다. <br>지원자 본인이 협업과 팀워크를 진행해보았던 경험과, 그 경험을 멋쟁이 사자처럼 대학에서 어떻게 적용시킬 수 있을지 작성해주세요. (500자 이내)</h4>
                            <div class="text-container dark">
                                <p class="testimonial-text">{{apply.third_q}}</p>
                            </div> <!-- end of text container -->

                            <h4>4. 멋쟁이사자처럼 대학은 최소 주 2회 모임 & 10시간 이상의 시간 투자를 권장합니다. <br>활동 기간동안 얼마나 열정적으로, 매주 얼만큼의 시간을 할애하실 수 있는지 작성해주세요. (500자 이내)</h4>
                            <div class="text-container dark">
                                <p class="testimonial-text">{{apply.fourth_q}}</p>
                            </div> <!-- end of text container -->

                            <h4>5. 깃허브 주소 혹은 블로그 링크</h4>
                            <div class="text-container dark">
                                <p class="testimonial-text"><a href="{{apply.study_url}}">{{apply.study_url}}</a></p>
                            </div> <!-- end of text container -->
                            {%if apply.is_submitted == False %}
                            <p>최종 제출을 누르고 나면 더 이상 수정하실 수 없습니다. 지원 시간 내에 최종 제출을 누르지 않으시면 지원하지 않은 것으로 간주됩니다.</p>
                            {% endif %}
                            </div> <!-- end of row -->
                        </div> <!-- end of text-container-->
                        {%if apply.is_submitted == False %}
                        <a class="btn-outline-reg" href="{% url 'apply:update' %}" onclick="alert('지원 기간이 종료되었습니다.');return false;">수정</a>
                        <a class="btn-outline-reg" href="{% url 'apply:submit' %}" onclick="alert('지원 기간이 종료되었습니다.');return false;">최종 제출</a>
                        {% endif %}
                    </div> <!-- end of col-->
                </div> <!-- end of row -->
            </div> <!-- end of container -->
        </div> <!-- end of ex-basic-2 -->
        <!-- end of privacy content -->
{% endblock %}

likelion10th/apply/templates/update.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<body data-spy="scroll" data-target=".fixed-top">
    
    <!-- Preloader -->
	<div class="spinner-wrapper">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->

    <!-- Header -->
    <header id="header" class="ex-2-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>지원서 작성</h1>
                    <p>문항을 읽고 지원서를 작성해주세요</p> 
                    <!-- apply Form -->
                    <div class="form-container" style="max-width: 80rem;">
                        <form action="{% url 'apply:update' %}" method="post">
                            {%csrf_token%}
                            <br>
                            <div class="form-group">
                                1. 다양한 IT동아리 중에서 멋쟁이사자처럼 대학 10기를 선택하고 지원하시게 된 이유를 작성해주세요. (500자 이내)
                                <textarea name="q1" class="form-control-input" rows="10">{{apply.first_q}}</textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <div class="form-group">
                                2-1. 멋쟁이사자처럼 대학 10기부터 기초 개발 스터디는 동일하게 진행되지만 이후에 기획/디자인 파트와 개발 파트 중 선택하여 진행하게 됩니다.<br>어느 파트에 지원하시나요?                                    
                                {% if apply.category == 'P/D' %}
                                <select style="width:300px" name="category" class="form-control-select" id="spassword">
                                    <option value="P/D" selected>기획/디자인</option>
                                    <option value="FE">프론트엔드</option>
                                    <option value="BE">백엔드</option>
                                </select>
                                {% elif apply.category == 'FE' %}
                                <select style="width:300px" name="category" class="form-control-select" id="spassword">
                                    <option value="P/D">기획/디자인</option>
                                    <option value="FE" selected>프론트엔드</option>
                                    <option value="BE">백엔드</option>
                                </select>
                                {% else %}
                                <select style="width:300px" name="category" class="form-control-select" id="spassword">
                                    <option value="P/D">기획/디자인</option>
                                    <option value="FE">프론트엔드</option>
                                    <option value="BE" selected>백엔드</option>
                                </select>        
                                {% endif %}
                            </div>
                            <br>
                            <div class="form-group">
                                2-2. 위의 파트를 선택한 이유와 관련 경험을 해본 적이 있는지, 그리고 이 파트를 통해 어떠한 성장을 희망하는지 작성해주세요. (500자 이내)
                                <textarea name="q2" class="form-control-input" rows="10">{{apply.second_q}}</textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <div class="form-group">
                                3. 멋쟁이사자처럼 대학은 협업과 팀워크를 중요한 가치로 생각하는 공동체입니다. 지원자 본인이 협업과 팀워크를 진행해보았던 경험과, 그 경험을<br>멋쟁이 사자처럼 대학에서 어떻게 적용시킬 수 있을지 작성해주세요. (500자 이내)
                                <textarea name="q3" class="form-control-input" rows="10">{{apply.third_q}}</textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <div class="form-group">
                                4. 멋쟁이사자처럼 대학은 최소 주 2회 모임 & 10시간 이상의 시간 투자를 권장합니다. 활동 기간 동안 얼마나 열정적으로, 매주 얼만큼의 시간을 할애하실 수 있는지 작성해주세요. (500자 이내)
                                <textarea name="q4" class="form-control-input" rows="10">{{apply.fourth_q}}</textarea>
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <div class="form-group">
                                5. 깃허브 주소 혹은 기술 블로그 링크 (선택 사항)
                                <input type="text" name="study_url" class="form-control-select" value={{apply.study_url}}>
                                <div class="help-block with-errors"></div>
                            </div>
                            <br>
                            <br>
                            <button type="submit" name="draft" class="form-control-submit-button">임시저장</button>
                        </form>
                    </div> <!-- end of form container -->
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header> <!-- end of ex-header -->
    <!-- end of header -->
{% endblock %}