likelion10th/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    #로그아웃 기능인데 혹시 필요할지도 몰라 만들어 보았습니다.
    path('logout/', views.Logout, name='logout'),
    #탈퇴 기능인데 혹시 필요할지도 몰라 만들어 보았습니다.
    path('secession/',views.secession, name='secession'),

    path('login/kakao/', views.kakao_login, name="kakao-login"),
    path('login/kakao/callback/', views.kakao_callback, name='kakao-callback'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy')
]

likelion10th/apply/urls.py
from unicodedata import name
from django.urls import path
from . import views #현재 폴더에 있는 views에 접근하기 때문

app_name = 'apply' # app_name에는 앱 이름을 넣어줍니다.

urlpatterns = [
    path('create/', views.create, name='create'),
    path('update/', views.update, name='update'),
    path('mypage/', views.mydetail, name='mydetail'),
    path('submit/', views.submit, name='submit')
]

likelion10th/likelion10th/urls.py
from django.contrib import admin
from django.urls import path, include
from apply import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('apply/', include('apply.urls')),
    path('account/', include('account.urls')),

    path('results/', include('pass_or_fail.urls')),
    
]

likelion10th/account/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)

#스터디에 사용했던 AbstractUser 은 필드가 너무 과한 면이 있습니다. (first name, last name 과 같은 정보를 받기 때문에) 
#그래서 어떤 모델을 사용할지 찾아보다가 AbstractBaseUser라는 모델을 사용하게 되었습니다. 

#이는 아래 grade 필드에서 사용되는 초이스 입니다. 우리가 흔히 웹사이트에서 무언가를 선택할 때 사용되는 select 안에 들어간다고 생각하시면 됩니다. 


'''학년 정보 선택 상자'''
GRADE_CHOICES = (
    ("1","1학년"),
    ("2","2학년"),
    ("3","3학년"),
    ("4","4학년"),
)


#AbstractBaseUser 에는 objects = UserManager() 이 있습니다. (이가 꼭 필요한 것 같습니다. 없으면 오류가 나더라고요)
#User 로 가입하고자 할 때 유효한 정보를 넘기는지 아닌지 검사하는 것이라고 생각하시면 될 것 같습니다. 
#이걸 헬퍼 클래스 라고 한다고 합니다..

class UserManager(BaseUserManager):
    # 유저를 생성할 때 이메일이 없다면 이메일이 있어야 한다는 오류를 발생시킵니다. 
    def create_user(self, email, password, name, student_num, phone_num, first_major):
        if not email:
            raise ValueError(("Users must have an email address"))
        # 유저 객체를 생성합니다.
        user = self.model(
            #normalize_email 이메일 정규화라고 하는데 예를 들어 이메일을 대문자로 입력했다면 소문자로 바꿔서 저장해주는 역할을 한다고 합니다. (확실하지는 않음..)
            email=self.normalize_email(email),
            name=name, 
            student_num=student_num, 
            phone_num=phone_num, 
            first_major=first_major,
        )
        #비밀번호 해시함수입니다.
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    #슈퍼유저를 생성하는 것이라면 이 함수를 실행시킵니다. 
    def create_superuser(self, email, password, name, student_num, phone_num, first_major):
        #유저의 email이라는 필드에 입력받은 email을, username이라는 필드에 username을, .. 넣어 저장합니다. 
        user = self.create_user(
            email=email,
            password=password,
            name=name, 
            student_num=student_num, 
            phone_num=phone_num, 
            first_major=first_major,

        )
        
        #슈퍼유저인지 아닌지에 대한 정보를 담습니다.
        user.is_superuser = True
        user.save()

        return user
    
#공통적으로 등장하는 verbose_name 은 db에서 보다 간편하게 필드가 무엇을 의미하는지 알 수 있도록 해주는 역할이라고 생각하시면 될 것 같습니다.
class User(AbstractBaseUser, PermissionsMixin):
    """Model definition for User."""

    #메인 유저의 아이디를 결정하는 부분입니다. 이메일 필드와 유저네임 필드의 역할이 겹치는 것 같아 이메일을 메인으로 설정하였습니다. 필요시 수정하겠습니다.
    USERNAME_FIELD = "email"

    #슈퍼유저 생성시 필수로 입력받고 싶은 값을 받는 부분입니다. NULL|BRANK 값이 FALSE값을 반드시 넣어주어야 합니다.
    REQUIRED_FIELDS = ['name','student_num','phone_num','first_major']

    objects = UserManager()

    email = models.EmailField(
        verbose_name=("email"),
        max_length=200,
        unique=True,
    )  

    name = models.CharField(
        max_length=20,
        verbose_name="이름",
    )

    student_num = models.CharField(
        verbose_name="학번",
        max_length=30,
    )

    grade = models.CharField(
        max_length=10,
        choices = GRADE_CHOICES,
        default="1",
        verbose_name="학년",
    )
    phone_num = models.CharField(
        max_length=20,
        verbose_name="휴대폰 번호",
    )

    first_major = models.CharField(
        max_length=30,
        verbose_name="본전공",
    )

    second_major = models.CharField(
        max_length=30,
        verbose_name="이중전공",
        null=True,
        blank=True,
    )

    is_accepted = models.BooleanField(
        default = False,
        verbose_name="합격 여부",
    )

    is_active = models.BooleanField(
        verbose_name=("Is active"),
        default=True,
    )

    # email field와 역할이 겹치는 면이 있는 것 같아 임시로 주석처리 하였습니다.
    # 기능상으로는 username이나 email중 어느 쪽을 사용해도 동일하니, 혹시라도 username이 꼭 필요한 것 같다는 의견이 있을시 수정하겠습니다.

    # username = models.CharField(
    #     verbose_name=("username"),
    #     max_length=50,
    #     unique=True,
    # ) 

    #class User(AbstractBaseUser, PermissionsMixin) 에서의 permissionmixin 에서 가져온 것입니다.
    # 이 부분은 그냥 넘기는게 나을 것 같습니다.
    @property
    def is_staff(self):
        return self.is_superuser

    class Meta:
        managed = False
        db_table = 'user'

likelion10th/account/forms.py
from django import forms
from . import models

class LoginForm(forms.Form):
  email=forms.EmailField(widget=forms.EmailInput({'placeholder': 'Email'}))
  password=forms.CharField(widget=forms.PasswordInput({'placeholder':'Password'}))

  def clean(self):
    email=self.cleaned_data.get('email')
    password=self.cleaned_data.get('password')

    try:
      user=models.User.objects.get(email=email)
      if user.check_password(password):
        return self.cleaned_data
      else:
        self.add_error('password', forms.ValidationError('password is wrong'))

    except models.User.DoesNotExist:
      self.add_error('email', forms.ValidationError('User does not exist'))

  # class Meta:
  #       model = models.User
  #   fields = ['Email','Password']

class SignUpform(forms.ModelForm):
  class Meta:
    model=models.User
    fields=('email','password','name','student_num','grade','phone_num','first_major','second_major')
    widgets={
      'email':forms.EmailInput(attrs={'class': "form-control-input", 'placeholder':'Email'}),
      'password':forms.PasswordInput(attrs={'class': "form-control-input", 'placeholder':'Password'}),
      'name':forms.TextInput(attrs={'class': "form-control-input", 'placeholder':'name'}),
      'student_num':forms.TextInput(attrs={'class': "form-control-input", 'placeholder':'student_num'}),
      'grade':forms.TextInput(attrs={'class': "form-control-input", 'placeholder':'grade'}),
      'phone_num':forms.TextInput(attrs={'class': "form-control-input", 'placeholder':'phone_num'}),
      'first_major':forms.TextInput(attrs={'class': "form-control-input", 'placeholder':'first_major'}),
      'second_major':forms.TextInput(attrs={'class': "form-control-input", 'placeholder':'second_major'}),
    }

    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'password'}))

  def clean_email(self):
    email=self.cleaned_data.get('email')
    try:
      models.User.objects.get(email=email)
      raise forms.ValidationError(
        'this email is already exist'
      )
    except models.User.DoesNotExist:
      return email

  def clean_password(self):
        password=self.cleaned_data.get('password')
        return password

  def save(self, *args, **kwargs):
        user=super().save(commit=False)
        email=self.cleaned_data.get('email')
        password=self.cleaned_data.get('password')
        user.username=email
        user.set_password(password)
        user.save()

likelion10th/account/views.py
import requests
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from  . import forms
from  django.views.generic import FormView
from  . import models as user_models


class LoginView(FormView):
    template_name="login.html"
    form_class=forms.LoginForm

    def form_valid(self, form):
        email=form.cleaned_data.get('email')
        password=form.cleaned_data.get('password')
        user=authenticate(self.request,username=email, password=password)

        if user is not None:
            login(self.request, user)
            
            print(user)

            return render(self.request, 'home.html')
        return super().form_vaild(form)

class SignUpView(FormView):
    template_name="signup.html"
    form_class=forms.SignUpform

    def form_valid(self,form):
        form.save()
        email=form.cleaned_data.get('email')
        password=form.cleaned_data.get('password')
        user=authenticate(self.request, username=email,password=password)
        if user is not None:
            login(self.request, user)

            return render(self.request, 'home.html')
        super(SignUpView,self).form_valid(form)

#로그아웃함수입니다. 필요시 사용하면 좋을것 같아 만들었습니다.
def Logout(request):

    logout(request)
    
    return redirect('home')

#탈퇴함수입니다. 필요시 사용하면 좋을것 같아 만들었습니다.
def secession(request):
    if request.method=='POST':
        input_password=request.POST['input_password']
        user=request.user.password
        print('입력:', input_password)
        print('비번:', user)
        if check_password(input_password, user):
            request.user.delete()
            logout(request)
            return render(request, 'login.html')

    return render(request, 'home.html')

class KakaoException(Exception):
      pass

def kakao_login(request):
    #이후 env 파일에 추가 필요
    rest_api_key= "6fec2af22db6826a94eba707eac15af5"
    #이후 도메인에 따른 수정 필요
    callback_url='http://127.0.0.1:8000/account/login/kakao/callback/'
    redirect_url= f"kauth.kakao.com/oauth/authorize?client_id={rest_api_key}&redirect_uri={callback_url}&response_type=code"
    return redirect(f"https://{redirect_url}")

def kakao_callback(request):
    try: 	
        rest_api_key= "6fec2af22db6826a94eba707eac15af5"
        callback_url='http://127.0.0.1:8000/account/login/kakao/callback/'
        code=request.GET.get("code")
            
        token_request= requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={rest_api_key}&redirect_uri={callback_url}&code={code}"
        )
        token_response_json=token_request.json()
        error=token_response_json.get("error",None)
        # print(f"token_response_json : {token_response_json}")

        if error is not None:
            raise KakaoException("can not import kakao authorization code.")

        access_token=token_response_json.get("access_token")
        profile_request=requests.get(
            "https://kapi.kakao.com/v2/user/me",
            headers={"Authorization": f"Bearer {access_token}"}
        )
        profile_json=profile_request.json()

        # print(f"Profile : {profile_json}")
        try:
            user=user_models.User.objects.get(email=profile_json.get("kakao_account").get("email"))
        except:
            user=user_models.User.objects.create(
                email=profile_json.get("kakao_account").get("email")
            )
            user.set_unusable_password()
            user.save()

        login(request,user)

        return render(request, 'home.html')
    except KakaoException as error:
        return redirect("account:signup")

def privacy_policy(request):
    return render(request, 'privacy-policy.html')

likelion10th/account/templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- SEO Meta Tags -->
    <meta name="description" content="Tivo is a HTML landing page template built with Bootstrap to help you crate engaging presentations for SaaS apps and convert visitors into users.">
    <meta name="author" content="Inovatik">

    <!-- OG Meta Tags to improve the way the post looks when you share the page on LinkedIn, Facebook, Google+ -->
	<meta property="og:site_name" content="" /> <!-- website name -->
	<meta property="og:site" content="" /> <!-- website link -->
	<meta property="og:title" content=""/> <!-- title shown in the actual shared post -->
	<meta property="og:description" content="" /> <!-- description shown in the actual shared post -->
	<meta property="og:image" content="" /> <!-- image link, make sure it's jpg -->
	<meta property="og:url" content="" /> <!-- where do you want your post to link to -->
	<meta property="og:type" content="article" />

    <!-- Website Title -->
    <title>Log In - Tivo - SaaS App HTML Landing Page Template</title>
    
    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap&subset=latin-ext" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet">
    <link href="{% static 'css/swiper.css' %}" rel="stylesheet">
	<link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">

	
</head>

<body data-spy="scroll" data-target=".fixed-top">
    <!-- Preloader -->
	<div class="spinner-wrapper">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->

    <!-- Header -->
    <header id="header" class="ex-2-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 style="color:#E67800">로그인</h1>
                   <p>혹시 아직 계정이 없으신가요?  <a class="white" href="{% url 'account:signup' %}" style="color:#E67800;">Sign Up</a></p> 
                    <!-- Sign Up Form -->
                    <div class="form-container">
                        <form action="{% url 'account:login' %}" method="POST" id="logInForm" data-toggle="validator" data-focus="false">
                          {% csrf_token %}  
                          <div class="form-group">
                                <input type="email" class="form-control-input" id="lemail" name="email" required>
                                <label class="label-control" for="lemail">이메일</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control-input" id="lpassword" name="password" required>
                                <label class="label-control" for="lpassword">비밀번호</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control-submit-button">LOG IN</button>
                            </div>
                            <div class="form-message">
                                <div id="lmsgSubmit" class="h3 text-center hidden"></div>
                            </div>
                        </form>

                        {% comment %} <div class="form-group">
                          <a href="{% url 'account:kakao-login' %}"><button type="button" class="form-control-submit-button">Kakao Login</button><a>
                        </div> {% endcomment %}

                    </div> <!-- end of form container -->
                    <!-- end of sign up form -->

                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header> <!-- end of ex-header -->
    <!-- end of header -->


    <!-- Scripts -->
    <script src="{% static 'js/jquery.min.js' %}"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
    <script src="{% static 'js/popper.min.js' %}"></script> <!-- Popper tooltip library for Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script> <!-- Bootstrap framework -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src="{% static 'js/swiper.min.js' %}"></script> <!-- Swiper for image and text sliders -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script> <!-- Magnific Popup for lightboxes -->
    {% comment %} <script src="{% static 'js/validator.min.js' %}"></script> <!-- Validator.js - Bootstrap plugin that validates forms --> {% endcomment %}
    <script src="{% static 'js/scripts.js' %}"></script> <!-- Custom scripts -->
</body>
</html>
{% endblock %}

likelion10th/account/templates/privacy-policy.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
    <!-- Header -->
    <header id="header" class="ex-header">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>개인 정보 수집 동의 안내</h1>
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header> <!-- end of ex-header -->
    <!-- end of header -->

    <!-- Privacy Content -->
    <div class="ex-basic-2">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-container">
                        <h3>[개인정보 수집·이용 동의서]</h3>
                        <p>주식회사 멋쟁이 사자처럼은 「정보통신망 이용촉진 및 정보보호에 관한 법률」 및 「개인정보보호법」 등 관련 법령상의 개인정보보호 규정을 준수하여 「22년 멋쟁이사자처럼 10기 모집」 참가자의 개인정보 및 권익을 보호하고, 개인정보와 관련한 참가자의 고충을 원활하게 처리할 수 있도록 다음과 같은 개인정보 처리방침을 두고 있습니다.</p>
                        <p>가. 개인 정보의 수집· 이용에 관한 사항</p>
                        <div class="row">
                            <div class="col-md-6">
                                <ul class="list-unstyled li-space-lg indent">
                                    <li class="media">
                                        <i class="fas fa-square"></i>
                                        <div class="media-body">개인 정보의 수집· 이용 목적<br>
                                            개인 정보는 1차적으로 본 프로그램 참가신청, 참가신청에 따른 본인확인, 개인식별, 프로그램 진행, 프로그램 관련 안내/고지사항 등의 전달, 문의사항 또는 불만사항 등의 확인 및 처리, 분쟁 조정을 위한 기록 보존 등을 위해 사용됩니다. 이후 멋쟁이사자처럼의 프로그램 및 브랜드 홍보를 위한 마케팅에 활용될 수 있습니다. </div>
                                    </li>
                                    <li class="media">
                                        <i class="fas fa-square"></i>
                                        <div class="media-body"> 수집하는 개인 정보의 항목<br>
                                            성명, 연락처, 이메일, 소속, 직업 등 신청 및 프로그램 운영 중 취득한 정보</div>
                                    </li>
                                    <li class="media">
                                        <i class="fas fa-square"></i>
                                        <div class="media-body">개인 정보의 보유· 이용기간<br>
                                            개인 정보는 원칙적으로 개인 정보의 수집 및 이용목적이 달성되면 지체 없이 파기합니다. 단, 본 사업 종료 후 참여 인정 문서 발급을 위한 최소한의 자료(성명, 전화번호, 이메일)는 사업종료 이후 5년간 보존됩니다.</div>
                                    </li>
                                    <li class="media">
                                        <i class="fas fa-square"></i>
                                        <div class="media-body">동의를 거부할 권리 및 동의를 거부할 경우의 불이익<br>
                                            위 개인 정보의 수집· 이용에 거부할 권리가 있음을 알려드립니다. 단, 수집항목은 사업 진행을 위한 최소한의 필수 정보로서 개인 정보 수집· 이용에 동의하지 않으실 경우 프로그램 참가 및 제반 활동이 불가능합니다.</div>
                                    </li>
                                </ul>
                            </div> <!-- end of col -->
                        </div> <!-- end of row -->
                        <br>
                        <p>나. 개인 정보 제3자 제공에 관한 사항</p>
                        <div class="row">
                            <div class="col-md-6">
                                <ul class="list-unstyled li-space-lg indent">
                                    <li class="media">
                                        <i class="fas fa-square"></i>
                                        <div class="media-body">제공받는 자<br>
                                            주식회사 멋쟁이사자처럼 </div>
                                    </li>
                                    <li class="media">
                                        <i class="fas fa-square"></i>
                                        <div class="media-body">제공받는 자의 목적<br>
                                            ‘22년 멋쟁이사자처럼 10기 모집’ 진행 및 운영, 참가자 관리, 마케팅 활용</div>
                                    </li>
                                    <li class="media">
                                        <i class="fas fa-square"></i>
                                        <div class="media-body">제공하는 개인 정보 항목<br>
                                            성명, 연락처, 이메일, 소속, 직업 등 신청 및 프로그램 운영 중 취득한 정보</div>
                                    </li>
                                    <li class="media">
                                        <i class="fas fa-square"></i>
                                        <div class="media-body">동의를 거부할 권리 및 동의를 거부할 경우의 불이익<br>
                                            위 제3자에 대한 개인 정보의 제공에 관한 동의를 거부할 수 있으나 본 프로그램 참가를 위해 필수적이므로 위 사항에 동의하셔야만 참가 및 활동이 가능합니다.</div>
                                    </li>
                                </ul>
                            </div> <!-- end of col -->
                        </div> <!-- end of row -->
                    </div> <!-- end of text-container-->
                    <a class="btn-outline-reg" href="{% url 'account:signup' %}">BACK</a>
                </div> <!-- end of col-->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </div> <!-- end of ex-basic-2 -->
    <!-- end of privacy content -->
{% endblock%}

likelion10th/account/templates/signup.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- SEO Meta Tags -->
    <meta name="description" content="Tivo is a HTML landing page template built with Bootstrap to help you crate engaging presentations for SaaS apps and convert visitors into users.">
    <meta name="author" content="Inovatik">

    <!-- OG Meta Tags to improve the way the post looks when you share the page on LinkedIn, Facebook, Google+ -->
	<meta property="og:site_name" content="" /> <!-- website name -->
	<meta property="og:site" content="" /> <!-- website link -->
	<meta property="og:title" content=""/> <!-- title shown in the actual shared post -->
	<meta property="og:description" content="" /> <!-- description shown in the actual shared post -->
	<meta property="og:image" content="" /> <!-- image link, make sure it's jpg -->
	<meta property="og:url" content="" /> <!-- where do you want your post to link to -->
	<meta property="og:type" content="article" />

    <!-- Website Title -->
    <title>Sign Up - Tivo - SaaS App HTML Landing Page Template</title>
    
    <!-- Styles -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700&display=swap&subset=latin-ext" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet">
    <link href="{% static 'css/swiper.css' %}" rel="stylesheet">
	<link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
	<link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body data-spy="scroll" data-target=".fixed-top">
    
    <!-- Preloader -->
	<div class="spinner-wrapper">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <!-- end of preloader -->
    

    <!-- Header -->
    <header id="header" class="ex-2-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 style="color:#E67800;">회원가입</h1>
                   <p>멋쟁이 사자처럼 회원가입을 위해 아래의 폼을 채워주세요<br>
                     이미 계정이 있으신가요? <a class="white" href="{% url 'account:login' %}" style="color:#E67800;">Log In</a></p> 
                    <!-- Sign Up Form -->
                    <div class="form-container">
                        <form action="{% url 'account:signup' %}" method="POST" id="signUpForm" >
                          {% csrf_token %}
                            <div class="form-group">
                                <input type="email" class="form-control-input" id="semail" name='email' required >
                                <label class="label-control" for="semail">이메일</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control-input" id="spassword" name='password' required>
                                <label class="label-control" for="spassword">비밀번호</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control-input" id="spassword" name='name' required>
                                <label class="label-control" for="spassword">성명</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control-input" id="spassword" name='student_num' required>
                                <label class="label-control" for="spassword">학번</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <select class="form-control-input" id="spassword" name='grade' required>
                                    <option value="none">학년</option>
                                    <option value="1">1학년</option>
                                    <option value="2">2학년</option>
                                    <option value="3">3학년</option>
                                    <option value="4">4학년</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control-input" id="spassword" name='phone_num' required>
                                <label class="label-control" for="spassword">휴대폰 번호</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control-input" id="spassword" name='first_major' required>
                                <label class="label-control" for="spassword">본 전공</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control-input" id="spassword" name='second_major'>
                                <label class="label-control" for="spassword">이중 전공</label>
                                <div class="help-block with-errors"></div>
                            </div>


                            <div class="form-group checkbox">
                                <input type="checkbox" id="sterms" value="Agreed-to-Terms" required> <a href="{% url 'account:privacy_policy' %}">개인정보 수집 및 이용</a>에 동의합니다
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control-submit-button">SIGN UP</button>
                            </div>

                            <div class="form-message">
                                <div id="smsgSubmit" class="h3 text-center hidden"></div>
                            </div>
                        </form>
                        
                        {% comment %} <div class="form-group">
                          <a href="{% url 'account:kakao-login' %}"><button type="button" class="form-control-submit-button">Kakao Login</button></a>
                        </div> {% endcomment %}

                    </div> <!-- end of form container -->
                    <!-- end of sign up form -->
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header> <!-- end of ex-header -->
    <!-- end of header -->


    <!-- Scripts -->
    <script src="{% static 'js/jquery.min.js' %}"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
    <script src="{% static 'js/popper.min.js' %}"></script> <!-- Popper tooltip library for Bootstrap -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script> <!-- Bootstrap framework -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src="{% static 'js/swiper.min.js' %}"></script> <!-- Swiper for image and text sliders -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script> <!-- Magnific Popup for lightboxes -->
    {% comment %} <script src="{% static 'js/validator.min.js' %}"></script> php로 가는 원인..<!-- Validator.js - Bootstrap plugin that validates forms --> {% endcomment %}
    <script src="{% static 'js/scripts.js' %}"></script> <!-- Custom scripts -->
</body>
</html>
{% endblock %}